### ISSUE TITLE
[BUG] Added events can not be monitored

### ISSUE THREAD

**Issue by Yakehira** [brittyazel/DevTool#10]
## Issue description:
Going to Events tab and adding any Event and starting monitoring, will result in no monitoring despite a message being printed that says "Start event monitoring: EventName"

## Technical info:
- **Addon Version:*** *1.0.4*
- **Client:** *Retail*
- **Client Patch Version:** *10.1.7*

**Comment by brittyazel** [comment]
Hrm mine are working just fine. Can I get an example of an event that you are having this issue with? And is it all events? Please test with a very verbose event such as COMBAT_LOG_EVENT_UNFILTERED

**Comment by Yakehira** [comment]
Any i add don't work, the ones that were already in the list form the start do work. Reloading after adding a event doesn't help, so when i add something like UPDATE_UI_WIDGET etc there is just nothing going on at all.

COMBAT_LOG_EVENT_UNFILTERED will work and it was already there by default for me.

**Comment by Yakehira** [comment]
Hmm interesting, some events do actually work? weird.
![image](https://github.com/brittyazel/DevTool/assets/773039/fa3a37bf-119c-483e-8f31-7ea7f299e63f)

**Comment by brittyazel** [comment]
Hrm, interesting. I'll look into replicating these the next time I'm on. Perhaps Blizz changed/broke something without announcing it, and/or they're throttling addon access to view events. This is very peculiar though, so thank you for reporting it.

**Comment by brittyazel** [comment]
Haven't had any free time to dig into it unfortunately. Once I get a moment I can jump in and see what Blizzard changed, no eta though. For now you can use the in-game event tool, which should be a good alternative until I can patch Dev Tool.

**Comment by brittyazel** [comment]
Nice, perfect. I'll test that and release a new version if it seems stable

**Comment by brittyazel** [comment]
Ok, please test this latest fix. If it works for y'all I'll push a new release. The issue was a dumb assumption I made about the payload values from events, and I believe this should correct it.
