### ISSUE TITLE
[Feature Request] Preserve shown state

### ISSUE THREAD

**Issue by Nnoggie** [brittyazel/DevTool#9]
Hello and thank you for continuing VDT!

VDT had the default behavior where it would pop up after a reload if it was also shown before that reload but DevTool does not have the same behavior, one has to open up the AddOn manually after every reload.
With how often reloads occur during AddOn development i really liked the behavior and would love to see it in DevTool. Maybe an option to enable it could be good?

Cheers!

**Comment by brittyazel** [comment]
This is a great suggestion, and shouldn't be too hard to implement. Thanks for suggesting it!

**Comment by brittyazel** [comment]
So I'm looking into this and this is defiantly already implemented and working... The fact that it's not working on your end is concerning. I can verify on my end that the code works as intended as-is and the visibility of the window returns after a /reload

**Comment by Nnoggie** [comment]
This was an issue on my side! It is working as expected.
